const allBooks = [
  {
    title: "The Enchanted Forest",
    author: "Alice Green",
    description: "A captivating tale of magic and mystery in a hidden forest.",
    publishedDate: "2022-03-15T00:00:00.000Z",
    cover: "http://example.com/enchantedforest.jpg",
    pdf: "http://example.com/enchantedforest.pdf",
    genres: "Fantasy",
    tags: ["Magic", "Adventure", "Mystery"],
  },
  {
    title: "Journey to the Stars",
    author: "Bob Black",
    description: "An epic journey through space exploring unknown galaxies.",
    publishedDate: "2021-11-22T00:00:00.000Z",
    cover: "http://example.com/journeytothestars.jpg",
    pdf: "http://example.com/journeytothestars.pdf",
    genres: "Science Fiction",
    tags: ["Space", "Adventure", "Sci-Fi"],
  },
  {
    title: "The Lost City",
    author: "Carol White",
    description:
      "A thrilling adventure to uncover the secrets of a lost civilization.",
    publishedDate: "2020-05-18T00:00:00.000Z",
    cover: "http://example.com/lostcity.jpg",
    pdf: "http://example.com/lostcity.pdf",
    genres: "Adventure",
    tags: ["Exploration", "History", "Thriller"],
  },
  {
    title: "Mysteries of the Deep",
    author: "David Blue",
    description: "A deep dive into the uncharted waters of the ocean.",
    publishedDate: "2019-08-30T00:00:00.000Z",
    cover: "http://example.com/mysteriesofthedeep.jpg",
    pdf: "http://example.com/mysteriesofthedeep.pdf",
    genres: "Non-Fiction",
    tags: ["Ocean", "Science", "Exploration"],
  },
  {
    title: "A Tale of Two Worlds",
    author: "Eva Gray",
    description: "A story of parallel worlds and the adventures within them.",
    publishedDate: "2018-12-14T00:00:00.000Z",
    cover: "http://example.com/taleoftwoworlds.jpg",
    pdf: "http://example.com/taleoftwoworlds.pdf",
    genres: "Fantasy",
    tags: ["Parallel Worlds", "Adventure", "Fantasy"],
  },
  {
    title: "The Silent Witness",
    author: "Frank Red",
    description: "A gripping mystery where silence holds the key to the truth.",
    publishedDate: "2017-04-27T00:00:00.000Z",
    cover: "http://example.com/silentwitness.jpg",
    pdf: "http://example.com/silentwitness.pdf",
    genres: "Mystery",
    tags: ["Detective", "Thriller", "Crime"],
  },
  {
    title: "Under the Northern Lights",
    author: "Grace Brown",
    description:
      "A romantic journey set against the backdrop of the Aurora Borealis.",
    publishedDate: "2016-09-09T00:00:00.000Z",
    cover: "http://example.com/northernlights.jpg",
    pdf: "http://example.com/northernlights.pdf",
    genres: "Romance",
    tags: ["Romance", "Nature", "Adventure"],
  },
  {
    title: "Secrets of the Ancient Temple",
    author: "Henry Gold",
    description: "Unraveling the secrets hidden within an ancient temple.",
    publishedDate: "2015-06-03T00:00:00.000Z",
    cover: "http://example.com/ancienttemple.jpg",
    pdf: "http://example.com/ancienttemple.pdf",
    genres: "Adventure",
    tags: ["Archaeology", "History", "Mystery"],
  },
  {
    title: "Chasing the Horizon",
    author: "Ivy Silver",
    description:
      "A story of endless pursuit and the challenges faced along the way.",
    publishedDate: "2014-01-25T00:00:00.000Z",
    cover: "http://example.com/chasinghorizon.jpg",
    pdf: "http://example.com/chasinghorizon.pdf",
    genres: "Drama",
    tags: ["Journey", "Life", "Inspiration"],
  },
  {
    title: "Voices in the Wind",
    author: "Jack White",
    description: "A collection of haunting tales carried by the wind.",
    publishedDate: "2013-10-19T00:00:00.000Z",
    cover: "http://example.com/voiceswind.jpg",
    pdf: "http://example.com/voiceswind.pdf",
    genres: "Horror",
    tags: ["Horror", "Thriller", "Mystery"],
  },
];

module.exports = allBooks;
